
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-password: secret
    key-alias: testserv-service
    key-store-password: secret
    trust-store: classpath:truststore.jks
    trust-store-password: secret
    client-auth: need
  servlet:
    context-path: /testserv
