
testserv:
  service:
    endpoint: https://localhost:8443/testserv/service
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-password: secret
    trust-store: classpath:truststore.jks
    trust-store-password: secret

